apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rs
  labels:
    env: frontend
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      env:  production
  replicas: 2   